"use client";

import { useState, type CSSProperties, type FormEvent } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import ArrowLeft01Icon from "@hugeicons/core-free-icons/ArrowLeft01Icon";
import ArrowRight01Icon from "@hugeicons/core-free-icons/ArrowRight01Icon";
import BankIcon from "@hugeicons/core-free-icons/BankIcon";
import Book01Icon from "@hugeicons/core-free-icons/Book01Icon";
import Calendar03Icon from "@hugeicons/core-free-icons/Calendar03Icon";
import CheckmarkCircle02Icon from "@hugeicons/core-free-icons/CheckmarkCircle02Icon";
import Invoice01Icon from "@hugeicons/core-free-icons/Invoice01Icon";
import MoneyReceive01Icon from "@hugeicons/core-free-icons/MoneyReceive01Icon";
import MoneySend01Icon from "@hugeicons/core-free-icons/MoneySend01Icon";
import Payment01Icon from "@hugeicons/core-free-icons/Payment01Icon";
import { StatusBadge } from "../components/ui";
import { formatIDR, payables, receivables } from "../data";
import type { CashAccount, LedgerRecord, PaymentHistoryRow, PaymentInput } from "../types";

type LedgerType = "AR" | "AP";

export function LedgerRecordDetail({ type, row, accounts, recordedPayments, back, recordPayment }: { type: LedgerType; row: LedgerRecord; accounts: CashAccount[]; recordedPayments: PaymentInput[]; back: () => void; recordPayment: (payment: PaymentInput) => void }) {
  const [tab, setTab] = useState("Overview");
  const [paymentOpen, setPaymentOpen] = useState(false);
  const isAR = type === "AR";
  const outstanding = row.total - row.paid;
  const settled = Math.round((row.paid / row.total) * 100);
  const seed = (isAR ? receivables : payables).find((item) => item.ref === row.ref);
  const formatPaymentDate = (value: string) => { const [year, month, day] = value.split("-"); return `${day} ${["Jan", "Feb", "Mar", "Apr", "Mei", "Jun", "Jul", "Agu", "Sep", "Okt", "Nov", "Des"][Number(month) - 1]} ${year}`; };
  const paymentRows: PaymentHistoryRow[] = [
    ...(seed && seed.paid > 0 ? [{ date: "12 Agu 2026", reference: `PAY-${row.ref.replace(/\W/g, "").slice(-8)}-01`, account: isAR ? "Giro BCA" : "Bank Operasional BCA", amount: seed.paid }] : []),
    ...recordedPayments.map((payment) => ({ date: formatPaymentDate(payment.date), reference: payment.reference, account: payment.account, amount: payment.amount })),
  ];
  const submitPayment = (payment: PaymentInput) => { recordPayment(payment); setPaymentOpen(false); };
  return <><button className="back-button account-back" onClick={back} type="button"><HugeiconsIcon icon={ArrowLeft01Icon} size={17} strokeWidth={1.8} /> Back to {isAR ? "Receivables" : "Payables"}</button><section className="ar-detail-hero"><div className={`ar-detail-icon ${isAR ? "receivable" : "payable"}`}><HugeiconsIcon icon={isAR ? MoneyReceive01Icon : MoneySend01Icon} size={25} strokeWidth={1.7} /></div><div className="ar-detail-title"><span>{isAR ? "ACCOUNTS RECEIVABLE" : "ACCOUNTS PAYABLE"}</span><h1>{row.ref}</h1><p>{row.party} · {row.project}</p></div><StatusBadge status={row.status} /><button className="primary-button" disabled={outstanding === 0} onClick={() => setPaymentOpen(true)} type="button"><HugeiconsIcon icon={Payment01Icon} size={18} strokeWidth={1.8} /> Record Payment</button></section><section className="ar-balance-strip"><div><span>Invoice Amount</span><strong>{formatIDR(row.total)}</strong><small>Original document value</small></div><div><span>Paid to Date</span><strong className="text-green">{formatIDR(row.paid)}</strong><small>{settled}% settled</small></div><div><span>Outstanding</span><strong className={outstanding ? "text-red" : "text-green"}>{formatIDR(outstanding)}</strong><small>{outstanding ? `Due ${row.due}` : "Fully settled"}</small></div><div className="settlement-progress"><span>Settlement Progress</span><strong>{settled}%</strong><div><i style={{ width: `${settled}%` }} /></div></div></section><div className="tabs account-detail-tabs">{["Overview", "Payment History", "Journal"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item} type="button">{item}</button>)}</div>{tab === "Overview" && <LedgerOverview type={type} row={row} outstanding={outstanding} settled={settled} openPayment={() => setPaymentOpen(true)} />}{tab === "Payment History" && <PaymentHistory row={row} payments={paymentRows} outstanding={outstanding} openPayment={() => setPaymentOpen(true)} />}{tab === "Journal" && <PaymentJournal type={type} row={row} paymentCount={paymentRows.length} />}{paymentOpen && <RecordPaymentModal type={type} row={row} accounts={accounts} close={() => setPaymentOpen(false)} submit={submitPayment} />}</>;
}

function LedgerOverview({ type, row, outstanding, settled, openPayment }: { type: LedgerType; row: LedgerRecord; outstanding: number; settled: number; openPayment: () => void }) {
  const isAR = type === "AR";
  return <div className="ar-detail-grid"><article className="panel"><div className="panel-head"><div><h2>Document Information</h2><p>Detail tagihan dan pihak terkait</p></div></div><dl className="account-info-list"><div><dt>Reference</dt><dd>{row.ref}</dd></div><div><dt>{isAR ? "Client" : "Vendor"}</dt><dd>{row.party}</dd></div><div><dt>Project</dt><dd>{row.project}</dd></div><div><dt>Issue Date</dt><dd>01 Agu 2026</dd></div><div><dt>Due Date</dt><dd>{row.due}</dd></div><div><dt>Current Status</dt><dd><StatusBadge status={row.status} /></dd></div></dl></article><article className="panel payment-summary-panel"><div className="panel-head"><div><h2>Payment Summary</h2><p>Posisi pembayaran dokumen</p></div></div><div className="payment-summary-visual"><div className={`payment-ring ${outstanding === 0 ? "complete" : ""}`} style={{ "--payment-progress": `${settled * 3.6}deg` } as CSSProperties}><span><strong>{settled}%</strong><small>settled</small></span></div><div className="payment-summary-values"><div><span>Document total</span><b>{formatIDR(row.total)}</b></div><div><span>Payments recorded</span><b className="text-green">{formatIDR(row.paid)}</b></div><div><span>Remaining balance</span><b className={outstanding ? "text-red" : "text-green"}>{formatIDR(outstanding)}</b></div></div></div>{outstanding > 0 && <button className="payment-callout" onClick={openPayment} type="button"><HugeiconsIcon icon={Payment01Icon} size={19} strokeWidth={1.8} /><span><b>Record the next payment</b><small>Maximum {formatIDR(outstanding)}</small></span><HugeiconsIcon icon={ArrowRight01Icon} size={17} strokeWidth={1.8} /></button>}</article></div>;
}

function PaymentHistory({ row, payments, outstanding, openPayment }: { row: LedgerRecord; payments: PaymentHistoryRow[]; outstanding: number; openPayment: () => void }) {
  return <article className="panel list-panel account-detail-table"><div className="ledger-toolbar"><div><h2>Payment History</h2><p>Seluruh pembayaran yang diterapkan ke dokumen ini</p></div>{outstanding > 0 && <button className="primary-button" onClick={openPayment} type="button"><HugeiconsIcon icon={Payment01Icon} size={18} strokeWidth={1.8} /> Record Payment</button>}</div><div className="table-wrap full-table"><table><thead><tr><th>Payment Date</th><th>Payment Reference</th><th>Cash Account</th><th>Method</th><th>Amount</th><th>Status</th></tr></thead><tbody>{payments.length ? payments.map((payment) => <tr key={payment.reference}><td><b>{payment.date}</b></td><td><b>{payment.reference}</b><small>Applied to {row.ref}</small></td><td>{payment.account}</td><td>Bank Transfer</td><td className="profit"><b>{formatIDR(payment.amount)}</b></td><td><StatusBadge status="POSTED" /></td></tr>) : <tr><td colSpan={6}><div className="empty-payment"><HugeiconsIcon icon={Payment01Icon} size={23} strokeWidth={1.6} /><b>No payment recorded</b><span>Record the first payment for this document.</span></div></td></tr>}</tbody></table></div></article>;
}

function PaymentJournal({ type, row, paymentCount }: { type: LedgerType; row: LedgerRecord; paymentCount: number }) {
  const isAR = type === "AR";
  return <article className="panel list-panel account-detail-table"><div className="ledger-toolbar"><div><h2>Automatic Journal</h2><p>Jurnal terbentuk otomatis dari dokumen dan pembayaran</p></div><span className="live-chip"><i />BALANCED</span></div><div className="table-wrap full-table"><table><thead><tr><th>Date / Reference</th><th>Account</th><th>Description</th><th>Debit</th><th>Credit</th></tr></thead><tbody><tr><td><b>01 Agu 2026</b><small>{row.ref}</small></td><td><b>{isAR ? "Accounts Receivable" : "Project Expense"}</b><small>{row.project}</small></td><td>Document recognition</td><td className="text-green">{formatIDR(row.total)}</td><td>—</td></tr><tr><td><b>01 Agu 2026</b><small>{row.ref}</small></td><td><b>{isAR ? "Project Revenue" : "Accounts Payable"}</b><small>{row.project}</small></td><td>Document recognition</td><td>—</td><td className="text-red">{formatIDR(row.total)}</td></tr>{row.paid > 0 && <><tr><td><b>Payment entries</b><small>{paymentCount} posted payment(s)</small></td><td><b>{isAR ? "Cash & Bank" : "Accounts Payable"}</b></td><td>Payment settlement</td><td className="text-green">{formatIDR(row.paid)}</td><td>—</td></tr><tr><td><b>Payment entries</b><small>Auto-generated</small></td><td><b>{isAR ? "Accounts Receivable" : "Cash & Bank"}</b></td><td>Payment settlement</td><td>—</td><td className="text-red">{formatIDR(row.paid)}</td></tr></>}</tbody></table></div><div className="ledger-note"><HugeiconsIcon icon={Book01Icon} size={18} strokeWidth={1.8} /><span><b>Journal is balanced</b><small>Debit and credit entries are generated automatically from the document lifecycle.</small></span></div></article>;
}

function RecordPaymentModal({ type, row, accounts, close, submit }: { type: LedgerType; row: LedgerRecord; accounts: CashAccount[]; close: () => void; submit: (payment: PaymentInput) => void }) {
  const outstanding = row.total - row.paid;
  const isAR = type === "AR";
  const [amount, setAmount] = useState(outstanding);
  const [account, setAccount] = useState(accounts[0]?.name ?? "Bank Operasional BCA");
  const [date, setDate] = useState("2026-08-21");
  const [reference, setReference] = useState(`PAY-${row.ref.replace(/\W/g, "").slice(-8)}-02`);
  const [notes, setNotes] = useState("");
  const valid = amount > 0 && amount <= outstanding && reference.trim().length > 2;
  const post = (event: FormEvent) => { event.preventDefault(); if (valid) submit({ amount, account, date, reference, notes }); };
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Record payment"><form className="modal-card payment-modal" onSubmit={post}><div className="modal-head"><div><span className="eyebrow">{isAR ? "RECEIVE PAYMENT" : "RECORD PAYMENT"}</span><h2>{isAR ? "Record customer payment" : "Record vendor payment"}</h2><p>Terapkan pembayaran ke {row.ref} dan posting jurnal otomatis.</p></div><button onClick={close} aria-label="Tutup" type="button">×</button></div><div className="payment-document-summary"><div className={isAR ? "receivable" : "payable"}><HugeiconsIcon icon={Invoice01Icon} size={22} strokeWidth={1.7} /></div><span><small>{row.ref}</small><b>{row.party}</b><em>{row.project}</em></span><strong><small>OUTSTANDING</small>{formatIDR(outstanding)}</strong></div><div className="payment-form"><label className="payment-amount-label">Payment Amount (IDR)<div className="payment-amount-input"><span>Rp</span><input type="number" min="1" max={outstanding} value={amount} onChange={(event) => setAmount(Number(event.target.value))} /></div>{amount > outstanding && <small className="field-error">Amount cannot exceed the outstanding balance.</small>}</label><div className="form-grid"><label>Payment Date<div className="field-with-icon"><HugeiconsIcon icon={Calendar03Icon} size={18} strokeWidth={1.7} /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div></label><label>Cash Account<div className="field-with-icon"><HugeiconsIcon icon={BankIcon} size={18} strokeWidth={1.7} /><select value={account} onChange={(event) => setAccount(event.target.value)}>{accounts.map((item) => <option key={item.name}>{item.name}</option>)}</select></div></label><label>Payment Method<select defaultValue="Bank Transfer"><option>Bank Transfer</option><option>Cash</option><option>Giro</option></select></label><label>Payment Reference<input value={reference} onChange={(event) => setReference(event.target.value)} /></label><label className="full">Notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional payment notes..." /></label></div></div><div className="payment-impact"><div><HugeiconsIcon icon={CheckmarkCircle02Icon} size={18} strokeWidth={1.8} /><span><b>After this payment</b><small>Remaining balance</small></span><strong>{formatIDR(Math.max(0, outstanding - amount))}</strong></div><p>Payment will update the cash account, document status, payment history, and balanced journal.</p></div><div className="modal-actions"><button className="text-button" onClick={close} type="button">Cancel</button><button className="primary-button" disabled={!valid} type="submit"><HugeiconsIcon icon={Payment01Icon} size={18} strokeWidth={1.8} /> Post Payment</button></div></form></div>;
}
