"use client";

import { FilterBar, PageIntro, StatusBadge } from "../components/ui";

export function MastersView({ notify, tab, setTab }: { notify: (message: string) => void; tab: string; setTab: (tab: string) => void }) {
  const accounts = [["1-1101", "Bank Operasional BCA", "ASSET", "Cash & Bank", "Corporate"], ["1-1201", "Kas Proyek", "ASSET", "Petty Cash", "Project"], ["4-1001", "Pendapatan Termin", "REVENUE", "Project Revenue", "Project"], ["5-1101", "Biaya Material", "EXPENSE", "Direct Cost", "Project"], ["6-1001", "Beban Kantor", "EXPENSE", "Corporate Expense", "Corporate"]];
  const contacts = [["PT Aruna Hospitality", "CLIENT", "Hotel Gamelan", "Rp 100.000.000"], ["Nusantara Living", "CLIENT", "Villa Ubud", "Rp 120.000.000"], ["UD Sinar Baja", "VENDOR", "Hotel Gamelan", "Rp 24.500.000"], ["PT Beton Perkasa", "VENDOR", "Villa Ubud", "Rp 44.000.000"]];
  const categories = [["Pendapatan Termin", "INCOME", "4-1001 · Pendapatan Termin", "Project"], ["Biaya Material", "EXPENSE", "5-1101 · Biaya Material", "Project"], ["Tenaga Kerja", "EXPENSE", "5-1201 · Tenaga Kerja", "Project"], ["Beban Kantor", "EXPENSE", "6-1001 · Beban Kantor", "Corporate"]];
  return <><PageIntro title="Master Data" description="Kelola akun, rekanan, dan kategori transaksi perusahaan." action={<button className="primary-button" onClick={() => notify(`Form tambah ${tab.toLowerCase()} dibuka.`)} type="button"><span>＋</span> Add {tab === "Chart of Accounts" ? "Account" : tab === "Contacts" ? "Contact" : "Category"}</button>} /><div className="tabs">{["Chart of Accounts", "Contacts", "Transaction Categories"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item} type="button">{item}</button>)}</div><article className="panel list-panel"><FilterBar><div className="search-box wide">⌕<input placeholder={`Search ${tab.toLowerCase()}...`} /></div><select><option>All Types</option><option>Asset</option><option>Expense</option></select><select><option>Active</option><option>Inactive</option></select></FilterBar><div className="table-wrap full-table"><table><thead><tr>{(tab === "Chart of Accounts" ? ["Code", "Account Name", "Type", "Category", "Scope", "Status"] : tab === "Contacts" ? ["Contact", "Type", "Related Project", "Outstanding", "Status", "Action"] : ["Category", "Type", "Mapped Account", "Scope", "Status", "Action"]).map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{tab === "Chart of Accounts" ? accounts.map((row) => <tr key={row[0]}><td><b>{row[0]}</b></td><td><b>{row[1]}</b></td><td><span className="type-pill">{row[2]}</span></td><td>{row[3]}</td><td>{row[4]}</td><td><StatusBadge status="ACTIVE" /></td></tr>) : (tab === "Contacts" ? contacts : categories).map((row) => <tr key={row[0]}><td><b>{row[0]}</b></td><td><span className="type-pill">{row[1]}</span></td><td>{row[2]}</td><td><b>{row[3]}</b></td><td><StatusBadge status="ACTIVE" /></td><td><button className="row-action" type="button">•••</button></td></tr>)}</tbody></table></div></article></>;
}
