"use client";

import { useState } from "react";
import { PageIntro, StatusBadge } from "../components/ui";

export function MigrationView({ notify }: { notify: (message: string) => void }) {
  const [step, setStep] = useState(0);
  const steps = ["Upload", "Validate", "Mapping", "Preview", "Import", "Reconciliation"];
  const advance = () => { if (step < steps.length - 1) setStep(step + 1); if (step === 4) notify("Import selesai. 1.248 baris berhasil diproses."); };
  return <><PageIntro title="Data Migration" description="Migrasi file Excel historis dengan validasi dan rekonsiliasi terkontrol." /><div className="migration-stepper">{steps.map((item, index) => <div className={`${index === step ? "active" : ""} ${index < step ? "done" : ""}`} key={item}><i>{index < step ? "✓" : index + 1}</i><span>{item}</span>{index < steps.length - 1 && <b />}</div>)}</div><article className="panel migration-card">{step === 0 && <div className="upload-zone"><div className="upload-cloud">⇧</div><h2>Upload your Excel files</h2><p>Tarik file ke area ini atau pilih dari komputer. Mendukung .xlsx dan .xls.</p><label className="primary-button file-button">Choose Files<input type="file" accept=".xlsx,.xls" onChange={() => setStep(1)} /></label><small>Maksimum 25 MB per file · Struktur asli tidak akan diubah</small></div>}{step === 1 && <MigrationValidation />}{step === 2 && <MigrationMapping />}{step === 3 && <MigrationPreview />}{step === 4 && <MigrationImport />}{step === 5 && <MigrationReconciliation />}{step > 0 && <div className="migration-actions"><button className="secondary-button" onClick={() => setStep(Math.max(0, step - 1))} type="button">← Previous</button>{step < 5 && <button className="primary-button" onClick={advance} type="button">{step === 4 ? "Import Data" : "Continue"} →</button>} {step === 5 && <button className="primary-button" onClick={() => setStep(0)} type="button">Finish Migration</button>}</div>}</article></>;
}

function MigrationValidation() { return <div className="migration-content"><div className="migration-title"><i className="success-ring">✓</i><div><h2>File structure validated</h2><p>3 workbook berhasil dibaca dan siap dipetakan.</p></div></div><div className="file-list"><div><span>Rekap_Keuangan_2025.xlsx<small>8 sheets · 824 rows</small></span><StatusBadge status="VALID" /></div><div><span>Cashflow_Project_2026.xlsx<small>5 sheets · 312 rows</small></span><StatusBadge status="VALID" /></div><div><span>Data_Hutang_Piutang.xlsx<small>2 sheets · 112 rows</small></span><StatusBadge status="WARNING" /></div></div><div className="warning-box">! 4 nama akun belum ditemukan pada Chart of Accounts dan perlu dipetakan.</div></div>; }
function MigrationMapping() { return <div className="migration-content"><div className="migration-title"><div><h2>Account & category mapping</h2><p>Padankan kolom Excel dengan master data sistem.</p></div><span className="mapping-progress">12 / 16 mapped</span></div><div className="mapping-table"><div className="mapping-head"><span>Excel value</span><span>System account</span><span>Status</span></div>{[["Biaya Tukang", "5-1201 · Tenaga Kerja", "MAPPED"], ["Besi & Baja", "5-1101 · Biaya Material", "MAPPED"], ["Kas Proyek GML", "1-1201 · Kas Proyek", "MAPPED"], ["Biaya Lain-Lain", "Select account...", "UNMAPPED"]].map((row) => <div key={row[0]}><b>{row[0]}</b><select defaultValue={row[1]}><option>{row[1]}</option><option>5-1901 · Biaya Lainnya</option></select><StatusBadge status={row[2]} /></div>)}</div></div>; }
function MigrationPreview() { return <div className="migration-content"><div className="migration-title"><div><h2>Import preview</h2><p>Periksa ringkasan data sebelum dimasukkan ke sistem.</p></div><span className="live-chip"><i />BALANCED</span></div><section className="mini-kpi-grid migration-kpis"><article><span>Transactions</span><strong>1.248</strong><small>1.104 posted · 144 draft</small></article><article><span>Total Debit</span><strong>Rp 8,42 M</strong><small>Across 1.248 records</small></article><article><span>Total Credit</span><strong>Rp 8,42 M</strong><small className="text-green">Difference Rp 0</small></article></section><div className="preview-table"><span>01 Jan 2025</span><b>Penerimaan termin proyek</b><span>Hotel Gamelan</span><strong>Rp 180.000.000</strong><StatusBadge status="READY" /></div><div className="preview-table"><span>03 Jan 2025</span><b>Pembelian material awal</b><span>Hotel Gamelan</span><strong>Rp 46.500.000</strong><StatusBadge status="READY" /></div></div>; }
function MigrationImport() { return <div className="migration-content import-state"><div className="import-art">⇩</div><h2>Ready to import 1.248 transactions</h2><p>Proses akan membuat jurnal berimbang, project allocation, dan audit log untuk setiap baris.</p><div className="impact-list"><span><i>✓</i> 1.248 transaction headers</span><span><i>✓</i> 2.496 balanced journal lines</span><span><i>✓</i> 16 cash accounts reconciled</span></div></div>; }
function MigrationReconciliation() { return <div className="migration-content"><div className="reconcile-hero"><div className="success-ring large">✓</div><h2>Migration completed & balanced</h2><p>Data sumber dan ledger sistem telah direkonsiliasi.</p></div><div className="reconcile-grid"><article><span>Source Total</span><strong>Rp 8.420.750.000</strong><small>Excel source · 1.248 rows</small></article><article><span>System Total</span><strong>Rp 8.420.750.000</strong><small>Posted ledger · 1.248 records</small></article><article className="balanced-card"><span>Difference</span><strong>Rp 0</strong><small>✓ Reconciliation balanced</small></article></div><div className="audit-note"><b>Audit package ready</b><span>Import log, mapping results, dan data mismatch report telah dibuat.</span><button type="button">Download package ⇩</button></div></div>; }
