"use client";

import { useState } from "react";
import { StatusBadge } from "../components/ui";
import { formatIDR } from "../data";
import type { Project, Transaction } from "../types";

export function ProjectDetail({ project, transactions, back }: { project: Project; transactions: Transaction[]; back: () => void }) {
  const [tab, setTab] = useState("Overview");
  const projectTransactions = transactions.filter((item) => item.project === project.name);
  const profit = project.revenue - project.expense;
  return <><button className="back-button" onClick={back} type="button">← Back to Projects</button><div className="detail-hero"><div className="project-monogram" style={{ background: project.color }}>{project.name.split(" ").map((word) => word[0]).join("")}</div><div><span className="eyebrow">{project.code}</span><h1>{project.name}</h1><p>{project.client} · {project.start} – {project.end}</p></div><StatusBadge status={project.status} /></div><div className="tabs">{["Overview", "Transactions", "Cash", "P&L", "Ledger"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item} type="button">{item}</button>)}</div>{tab === "Overview" && <><section className="mini-kpi-grid project-kpis"><article><span>Contract Revenue</span><strong>{formatIDR(project.revenue)}</strong><small>100% contract value</small></article><article><span>Total Expense</span><strong>{formatIDR(project.expense)}</strong><small>{Math.round((project.expense / project.revenue) * 100)}% of revenue</small></article><article><span>Net Profit</span><strong className="text-green">{formatIDR(profit)}</strong><small>Margin {Math.round((profit / project.revenue) * 100)}%</small></article></section><div className="two-column"><article className="panel"><div className="panel-head"><div><h2>Financial Progress</h2><p>Ringkasan realisasi proyek</p></div></div><div className="progress-row"><span>Revenue recognized <b>{formatIDR(project.revenue)}</b></span><div><i style={{ width: "78%" }} /></div><small>78% dari nilai kontrak</small></div><div className="progress-row expense-progress"><span>Expense realized <b>{formatIDR(project.expense)}</b></span><div><i style={{ width: "63%" }} /></div><small>63% dari estimasi operasional</small></div></article><article className="panel"><div className="panel-head"><div><h2>Recent Activity</h2><p>Transaksi terbaru proyek</p></div></div><div className="activity-list">{projectTransactions.slice(0, 3).map((tx) => <div key={tx.id}><i className={tx.type.toLowerCase()}>{tx.type === "Income" ? "+" : "−"}</i><span><b>{tx.description}</b><small>{tx.date} · {tx.account}</small></span><strong>{tx.type === "Income" ? "+" : "−"}{formatIDR(tx.amount).replace("Rp ", "Rp")}</strong></div>)}</div></article></div></>}{tab !== "Overview" && <article className="panel section-placeholder"><div className="section-icon">{tab === "P&L" ? "▥" : tab === "Cash" ? "▣" : "↕"}</div><h2>{tab} — {project.name}</h2><p>Data {tab.toLowerCase()} sudah terhubung ke project dan periode aktif.</p>{tab === "P&L" && <div className="statement compact"><div><span>Revenue</span><strong>{formatIDR(project.revenue)}</strong></div><div><span>Project expenses</span><strong>({formatIDR(project.expense)})</strong></div><div className="statement-total"><span>Net project profit</span><strong>{formatIDR(profit)}</strong></div></div>}</article>}</>;
}
