"use client";

import { useState } from "react";
import { PageIntro, StatusBadge } from "../components/ui";

export function SettingsView({ notify }: { notify: (message: string) => void }) {
  const [tab, setTab] = useState("Company");
  return <><PageIntro title="Settings" description="Konfigurasi profil perusahaan, pengguna, dan preferensi dasar." /><div className="settings-layout"><aside>{["Company", "Users", "Accounting", "System"].map((item) => <button className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item} type="button">{item}</button>)}</aside><article className="panel settings-card"><h2>{tab} Settings</h2><p>Kelola konfigurasi {tab.toLowerCase()} untuk aplikasi CKJS Finance.</p>{tab === "Company" ? <div className="form-grid"><label className="full">Company Name<input defaultValue="CV. Cipta Karya Jaya Sentosa" /></label><label>Business Type<input defaultValue="Construction & Contractor" /></label><label>Tax ID / NPWP<input defaultValue="—" /></label><label>Phone<input defaultValue="+62 812 3456 7890" /></label><label>Email<input defaultValue="finance@ckjs.co.id" /></label><label className="full">Address<textarea defaultValue="Denpasar, Bali, Indonesia" /></label></div> : tab === "Users" ? <div className="user-list"><div><div className="avatar">JI</div><span><b>Jason Ibrahim</b><small>jason@ckjs.co.id · Owner / Director</small></span><StatusBadge status="ACTIVE" /></div><div><div className="avatar second">CO</div><span><b>Co-Owner CKJS</b><small>owner2@ckjs.co.id · Owner / Director</small></span><StatusBadge status="ACTIVE" /></div><div className="future-role">Finance/Admin dan Site Supervisor tersedia sebagai future-ready role, tanpa workflow Phase 1.</div></div> : <div className="setting-options"><label aria-label="Accounting basis" htmlFor="setting-accounting-basis"><span><b>Accounting basis</b><small>Metode pengakuan pendapatan sistem</small></span><select id="setting-accounting-basis"><option>Cash basis</option></select></label><label aria-label="Transaction numbering" htmlFor="setting-transaction-numbering"><span><b>Transaction numbering</b><small>Format nomor transaksi otomatis</small></span><input id="setting-transaction-numbering" defaultValue="TX-YYYYMM-####" /></label><label aria-label="Default currency" htmlFor="setting-default-currency"><span><b>Default currency</b><small>Mata uang untuk semua laporan</small></span><select id="setting-default-currency"><option>IDR — Indonesian Rupiah</option></select></label></div>}<div className="settings-save"><button className="primary-button" onClick={() => notify(`${tab} settings berhasil disimpan.`)} type="button">Save Changes</button></div></article></div></>;
}
