"use client";

import { StatusBadge } from "./ui";
import { formatIDR } from "../data";
import type { Transaction } from "../types";

export function TransactionDetail({ transaction, close, reverse }: { transaction: Transaction; close: () => void; reverse: (tx: Transaction) => void }) {
  return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label="Transaction detail"><div className="modal-card detail-modal"><div className="modal-head"><div><span className="eyebrow">{transaction.id}</span><h2>Transaction Detail</h2><p>{transaction.date} · Created by Jason Ibrahim</p></div><button onClick={close} aria-label="Tutup" type="button">×</button></div><div className="detail-status-row"><StatusBadge status={transaction.status} /><span>{transaction.type}</span></div><div className="detail-amount"><span>Total Amount</span><strong>{formatIDR(transaction.amount)}</strong><p>{transaction.description}</p></div><dl className="detail-grid"><div><dt>Project / Scope</dt><dd>{transaction.project}</dd></div><div><dt>Category</dt><dd>{transaction.category}</dd></div><div><dt>Cash Account</dt><dd>{transaction.account}</dd></div><div><dt>Contact</dt><dd>{transaction.contact}</dd></div></dl><div className="journal-preview detail-journal"><div className="journal-head"><div><h3>Journal Entry</h3><p>Automatic double-entry lines</p></div><span className="balanced">✓ BALANCED</span></div><div className="journal-lines"><div className="journal-label"><span>Account</span><span>Debit</span><span>Credit</span></div><div><span><b>{transaction.type === "Expense" ? transaction.category : transaction.account}</b><small>{transaction.project}</small></span><strong>{formatIDR(transaction.amount)}</strong><strong>—</strong></div><div><span><b>{transaction.type === "Expense" ? transaction.account : transaction.category}</b><small>{transaction.contact}</small></span><strong>—</strong><strong>{formatIDR(transaction.amount)}</strong></div></div><div className="journal-total"><span>Total</span><strong>{formatIDR(transaction.amount)}</strong><strong>{formatIDR(transaction.amount)}</strong></div></div><div className="audit-strip"><i>✓</i><span><b>Audit trail verified</b><small>Posted 18 Agu 2026, 10:42 WIB by Jason Ibrahim</small></span></div><div className="modal-actions">{transaction.status === "DRAFT" && <button className="secondary-button" type="button">Edit Draft</button>}{transaction.status === "POSTED" && <button className="danger-button" onClick={() => reverse(transaction)} type="button">Reverse Transaction</button>}<button className="primary-button" onClick={close} type="button">Close</button></div></div></div>;
}
